### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by MOAboAli** [google/tirg#2]
-I faced number of problems running Main class but it worked after i run below
 python main.py --dataset=css3d --dataset_path=./CSSDataset --num_iters=160000   --model=tirg --loss=soft_triplet --comment=css3d_tirg --loader_num_workers=0

-another problem was project is python 2 currently python 3 but i succeed to change syntax 
-the problem which i couldn't find solution is ".cuda()" i don't have Nvidia Card ,i don't know what it do as i am new to python , so i comment all code has cuda, if can you tell me what it do and alternative for it , it would be great.
- also after training how can i enter query image and text  to get retrieved image ?

**Comment by mohamedaboali1990** [comment]
@luowy1001 can you help me on this ?

**Comment by satojkovic** [comment]
Hi @mohamedaboali1990 

When you want to run on CPU, you should use torch.cuda.is_available().
torch.cuda.is_available() returns a bool indicating whether CUDA is available or not.
If you want to know how to use this, please refer to my forked repository and last commit. 
https://github.com/satojkovic/tirg/commit/26fce87b3a7669eb3cdae2f84385ba885f751e23

**Comment by mohamedaboali1990** [comment]
@satojkovic , thank you for your reply , do you have an idea how to enter query image and text to  get retrieved image?
