### ISSUE TITLE
Running the trained model with a query image and text

### ISSUE THREAD

**Issue by qaziabubakar** [google/tirg#3]
I have the training code running and the model is being trained but I want to know how I can test that out using a query image and a query text, even with a pre trained model?

**Comment by lugiavn** [comment]
You can refer to pytorch documents on how to run a model or load a trained model.
To do a retrieval test, you can use this as an example: https://github.com/google/tirg/blob/master/test_retrieval.py

**Comment by timoderbeste** [comment]
> You can refer to pytorch documents on how to run a model or load a trained model.
> To do a retrieval test, you can use this as an example: https://github.com/google/tirg/blob/master/test_retrieval.py

I read the code but there does not seem to be any indication of loading a pretrained model? Assuming I would like to load a pretrained TIRG model for the Fashion200K dataset. Do I still need to first instantiate a TIRG model before I can load the state dict?
